uiPort = 5173

[[apps]]
name = "test-app"
execute = "notepad"
appPath = ""
appType = "other"
daemon = true
args = ""
autostart = false
timeout = 60
port = 0

[[apps]]
name = "ping-test"
execute = "ping"
appPath = "127.0.0.1"
appType = "other"
daemon = true
args = "-t"
autostart = false
timeout = 60
port = 0

[[apps]]
name = "python-test"
execute = "python"
appPath = "e:\\work\\anyrun\\test-project\\simple_server.py"
appType = "python"
daemon = true
args = ""
autostart = false
timeout = 60
port = 5000